# Generated by Django 2.2.14 on 2021-02-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
