# Generated by Django 2.2.14 on 2021-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0010_auto_20210213_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/carbon_1.png', null=True, upload_to=''),
        ),
    ]
